[color-theme]
name = 'Material Theme'

[color-theme.base]
black = '#282C34'
blue = '#82AAFF'
cyan = '#89DDFF'
green = '#C3E88D'
grey = '#3E4451'
magenta = '#C792EA'
orange = '#F78C6C'
purple = '#C792EA'
red = '#F07178'
white = '#ABB2BF'
yellow = '#FFCB6B'

[color-theme.syntax]
attribute = '$yellow'
builtinType = '$cyan'
comment = '#546E7A'
constant = '$orange'
constructor = '$blue'
embedded = '$cyan'
enum = '$purple'
enum-member = '$red'
enumMember = '$red'
escape = '$cyan'
field = '$red'
function = '$blue'
"function.method" = '$blue'
interface = '$yellow'
keyword = '$orange'
"keyword.control" = '$orange'
method = '$blue'
number = '$yellow'
property = '$red'
"punctuation.delimiter" = '$cyan'
selfKeyword = '$purple'
string = '$green'
"string.escape" = '$cyan'
struct = '$yellow'
structure = '$yellow'
symbol = '$yellow'
tag = '$blue'
"text.reference" = '$yellow'
"text.title" = '$orange'
"text.uri" = '$cyan'
type = '$yellow'
"type.builtin" = '$yellow'
typeAlias = '$yellow'
variable = '#EEFFFF'
"variable.other.member" = '#EEFFFF'

[color-theme.ui]
"activity.background" = '#21252B'
"activity.current" = '$black'
"completion.background" = '#21252B'
"completion.current" = '#2C313A'
"completion_lens.foreground" = '#5C6370'
"debug.breakpoint" = '$red'
"debug.breakpoint.hover" = '#E06C7566'
"editor.background" = '#263238'
"editor.caret" = '#FFCC00'
"editor.current_line" = '#00000050'
"editor.debug_break_line" = '#528abF37'
"editor.dim" = '#5C6370'
"editor.drag_drop_background" = '#79c1fc55'
"editor.drag_drop_tab_background" = '#0b0e1455'
"editor.focus" = '#FFFFFF'
"editor.foreground" = '#EEFFFF'
"editor.indent_guide" = '$grey'
"editor.link" = '$blue'
"editor.selection" = '#80CBC420'
"editor.sticky_header_background" = '#37474F'
"editor.visible_whitespace" = '$grey'
"error_lens.error.background" = '#E06C7520'
"error_lens.error.foreground" = '$red'
"error_lens.other.background" = '#5C637020'
"error_lens.other.foreground" = '#5C6370'
"error_lens.warning.background" = '#E5C07B20'
"error_lens.warning.foreground" = '$yellow'
"hover.background" = '#21252B'
"inlay_hint.background" = '#528abF37'
"inlay_hint.foreground" = '$white'
"lapce.border" = '#37474F'
"lapce.button.primary.background" = '#50a14f'
"lapce.button.primary.foreground" = '$black'
"lapce.dropdown_shadow" = '#000000'
"lapce.error" = '$red'
"lapce.icon.active" = '#6C8692'
"lapce.icon.inactive" = '#546E7A'
"lapce.plugin.author" = '#B0B0B0'
"lapce.plugin.description" = '$white'
"lapce.plugin.name" = '#DDDDDD'
"lapce.remote.connected" = '#50A14F'
"lapce.remote.connecting" = '#C18401'
"lapce.remote.disconnected" = '#E45649'
"lapce.remote.icon" = '$black'
"lapce.remote.local" = '#4078F2'
"lapce.scroll_bar" = '#EEFFFF20'
"lapce.tab.active.background" = '$black'
"lapce.tab.active.foreground" = '$white'
"lapce.tab.active.underline" = '#80CBC4'
"lapce.tab.inactive.background" = '#21252b'
"lapce.tab.inactive.foreground" = '$white'
"lapce.tab.inactive.underline" = '#528BFF77'
"lapce.tab.separator" = ''
"lapce.warn" = '$yellow'
"markdown.blockquote" = '#898989'
"palette.background" = '#263238'
"palette.current.background" = '#00000050'
"palette.current.foreground" = '$white'
"palette.foreground" = '$white'
"panel.background" = '#263238'
"panel.current.background" = '#00000050'
"panel.current.foreground" = '$white'
"panel.current.foreground.dim" = '#5C6370'
"panel.foreground" = '#6C8692'
"panel.foreground.dim" = '#5C6370'
"panel.hovered.active.background" = '#5C6370'
"panel.hovered.background" = '#EEFFFF10'
"panel.hovered.foreground" = '$white'
"panel.hovered.foreground.dim" = '#5C6370'
"source_control.added" = '#50A14FCC'
"source_control.modified" = '#0184BCCC'
"source_control.removed" = '#FF5266CC'
"status.background" = '#263238'
"status.foreground" = '#546E7A'
"status.modal.insert.background" = '$red'
"status.modal.insert.foreground" = '$black'
"status.modal.normal.background" = '$blue'
"status.modal.normal.foreground" = '$black'
"status.modal.terminal.background" = '$purple'
"status.modal.terminal.foreground" = '$black'
"status.modal.visual.background" = '$yellow'
"status.modal.visual.foreground" = '$black'
"terminal.background" = '$black'
"terminal.black" = '$black'
"terminal.blue" = '$blue'
"terminal.bright_black" = '#545862'
"terminal.bright_blue" = '$blue'
"terminal.bright_cyan" = '$cyan'
"terminal.bright_green" = '$green'
"terminal.bright_magenta" = '$magenta'
"terminal.bright_red" = '$red'
"terminal.bright_white" = '#C8CCD4'
"terminal.bright_yellow" = '$yellow'
"terminal.cursor" = '$white'
"terminal.cyan" = '$cyan'
"terminal.foreground" = '$white'
"terminal.green" = '$green'
"terminal.magenta" = '$magenta'
"terminal.red" = '$red'
"terminal.white" = '$white'
"terminal.yellow" = '$yellow'

[ui]
drop-shadow-width = 0
font-family = ''
font-size = 13
header-height = 35
hover-font-family = ''
hover-font-size = 0
icon-size = 0
list-line-height = 25
preview-editor-width = 0
scroll-width = 10
status-height = 25
tab-close-button = 'Right'
tab-min-width = 100
trim-search-results-whitespace = true
